name: superbot
description: A prototype for an app that enables undergraduate/postgraduate students working on their projects to readily gain access to related advice, recommendations and resources via an interactive chat-bot trained on data from both the students and their project supervisors
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  path_provider: ^2.1.1
  hydrated_bloc: ^9.1.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
